### PR TITLE
1.36.0

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
Thanks for the PR ! Just a small question, why did you increase the required Yunohost version ?

**Comment by ericgaspar** [comment]
Mmmh yeah, I wanted to add a `--keep` option on upgrade script but got discouraged... I put the version back to 4.1.0

**Comment by Salamandar** [comment]
OK, what's this `--keep` util ?

**Comment by ericgaspar** [comment]
> OK, what's this `--keep` util ?

https://github.com/yunohost/yunohost/pull/1200 👀

**Comment by Salamandar** [comment]
Oh ! :)

**Pull request merged**
