### PR TITLE
Update ldap_authentication2.src

### PR DESCRIPTION
**Pull request by Arxwel**
## Problem
- Installation failed because the extension was updated and the version in the configuration was not available anymore

## Solution
- Updated the configuration file to use the latest compatible version

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** :
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/mediawiki_ynh%20PR32/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
If we keep this upgrade from commit test, the CI will keep failing... 
https://github.com/YunoHost-Apps/mediawiki_ynh/blob/001a5d25c0b5c180456b5e8dffbd5a5ad8032124/check_process#L19

**Comment by ericgaspar** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by Salamandar** [comment]
LGTM.

**Comment by Salamandar** [comment]
When I have the time, I'll make an account on the mediawiki forum and ask them to stop deleting archives.

**Pull request merged**
