### PR TITLE
Ldap

### PR DESCRIPTION
**Pull request by kay0u**
Add ldap conf file.

Install script works.

Need to update upgrade script like I updated the install script (but we have to keep the secret key defined in install script)
Change the level 4 in check_process to "1" :-)

Reach level 7 \o/

### CODE REVIEW

**Comment by toitoinebzh** [comment]
Hi @kay0u 

Thank you for this PR.
[Mediawiki](https://www.mediawiki.org/wiki/Extension:LDAP_Authentication) reports that LdapAuthentication in unmaintained and does not work well with last version of Mediawiki.

> Does not work 100% on MediaWiki >= 1.27 - AutoAuth (Kerberos and smart card) does not work and no workaround unless re-code PHP.

are you sure that we can trust this plugin ?

**Comment by kay0u** [comment]
It's in red but I missed that part :-) I'll check if another extension couldn't be used

**Comment by kay0u** [comment]
We can find some doc here: https://www.mediawiki.org/wiki/LDAP_Stack

**Comment by kay0u** [comment]
A new extension exists for LDAP:

https://www.mediawiki.org/wiki/Extension:LDAPAuthorization

Maybe one day™  I'll try something.

**Comment by decentral1se** [comment]
<3

**Comment by decentral1se** [comment]
OK, I'm chasing the lead in https://github.com/YunoHost-Apps/mediawiki_ynh/pull/3#issuecomment-469682219 over at https://github.com/YunoHost-Apps/mediawiki_ynh/issues/5. Thanks for this PR, it was very helpful to get me started! Aiming to get #5 done Soon TM.

**Pull request closed without merging**
